Finished packaging for com.openexchange.eas.provisioning.action.mail

diff --git a/open-xchange-eas-provisioning/debian/open-xchange-eas-provisioning-core.postrm b/open-xchange-eas-provisioning/debian/open-xchange-eas-provisioning-core.postrm
--- a/open-xchange-eas-provisioning/debian/open-xchange-eas-provisioning-core.postrm
+++ b/open-xchange-eas-provisioning/debian/open-xchange-eas-provisioning-core.postrm
@@ -1,15 +1,20 @@
 #!/bin/bash
-# preinst script for open-xchange-eas-provisioning
+# postrm script for open-xchange-eas-provisioning
 #
 # see: dh_installdeb(1)
 
 set -e
 
 # summary of how this script can be called:
-#        * <new-preinst> `install'
-#        * <new-preinst> `install' <old-version>
-#        * <new-preinst> `upgrade' <old-version>
-#        * <old-preinst> `abort-upgrade' <new-version>
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
@@ -17,20 +22,19 @@ set -e
 TEMPLATES="iPhoneTemplate.tmpl mobile.configuration.generator.properties winMobileTemplate.tmpl"
 
 case "$1" in
-    install|upgrade)
-        if dpkg --compare-versions "$2" lt "6.21.0-0"; then
-            for FILE in ${TEMPLATES}; do
-                dpkg-divert --package open-xchange-eas-provisioning --add --rename --divert /opt/open-xchange/templates/${FILE}.dpkg-bak \
-                    /opt/open-xchange/templates/${FILE}
-            done
-        fi
+    remove|abort-install|disappear)
+        for FILE in ${TEMPLATES}; do
+            dpkg-divert --package open-xchange-eas-provisioning --remove --rename --divert /opt/open-xchange/templates/${FILE}.dpkg-bak \
+                /opt/open-xchange/templates/${FILE}
+            rm -f /opt/open-xchange/templates/${FILE}
+        done
     ;;
 
-    abort-upgrade)
+    purge|upgrade|failed-upgrade|abort-upgrade)
     ;;
 
     *)
-        echo "preinst called with unknown argument \`$1'" >&2
+        echo "postrm called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
@@ -43,7 +47,7 @@ dpkg-maintscript-helper mv_conffile /opt/open-xchange/etc/groupware/mobilityconf
     $(dpkg-query -W -f='${Config-Version}' open-xchange-mobile-configuration-json)
 dpkg-maintscript-helper mv_conffile /opt/open-xchange/etc/groupware/settings/open-xchange-mobile-configuration-gui.properties \
     /opt/open-xchange/etc/settings/eas-provisioning-ui.properties 6.20.99 open-xchange-mobile-configuration-json -- $1 \
-    $(dpkg-query -W -f='${Config-Version}' open-xchange-mobile-configuration-json
+    $(dpkg-query -W -f='${Config-Version}' open-xchange-mobile-configuration-json)
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
