US 73804270: generatempasswd.in shell script

diff --git a/com.openexchange.admin.console/sbin/generatempasswd.in b/com.openexchange.admin.console/sbin/generatempasswd.in
--- a/com.openexchange.admin.console/sbin/generatempasswd.in
+++ b/com.openexchange.admin.console/sbin/generatempasswd.in
@@ -1,4 +1,5 @@
-#! /usr/bin/perl -w
+#!/bin/bash
+#
 #
 #   OPEN-XCHANGE legal information
 #
@@ -45,78 +46,34 @@
 #    with this program; if not, write to the Free Software Foundation, Inc., 59
 #    Temple Place, Suite 330, Boston, MA 02111-1307 USA
 #
+#
 
-use strict;
-use Getopt::Long qw(:config no_ignore_case);
-
-my $OXMASTER   = "oxadminmaster";
-my $OXMPWFILE  = "@confDir@/mpasswd";
-my $OXPASSWORD = undef;
-my $USAGE      = undef;
-
-GetOptions( "adminuser|A=s"   => \$OXMASTER,
-            "adminpass|P=s"   => \$OXPASSWORD,
-            "mpasswdfile|f=s" => \$OXMPWFILE,
-            "help|h|?"        => \$USAGE
-) || die;
+OXFUNCTIONS=@oxfunctions@
+OXCONFIG=@oxscriptconf@
 
 if( $< != 0 ) {
 	die "You must be root to run this command";
 }
 
-usage() if ! defined $OXMASTER || ! defined $OXMPWFILE || defined $USAGE;
-
-my $cryptedpw = undef;
-if( ! defined $OXPASSWORD ) {
-	$cryptedpw=encryptPassword(promptPassword());
-} else {
-	$cryptedpw=encryptPassword($OXPASSWORD);
+test -f $OXFUNCTIONS || {
+    echo "missing common shell functions file"
+    exit 1
 }
 
-if( defined $cryptedpw && length($cryptedpw)>0 ) {
-	open(OUT,">$OXMPWFILE") || die "unable to open $OXMPWFILE: $!";
-	print OUT "$OXMASTER:$cryptedpw\n";
-	close(OUT);
-	print "saved password for user $OXMASTER in $OXMPWFILE\n";
-}
+. $OXFUNCTIONS
 
+test -f $OXCONFIG && . $OXCONFIG
 
+ox_set_JAVA_BIN
 
-1;
-# ---------------------------------- functions -------
+test -z "$JAVA_OXCMD_OPTS" && JAVA_OXCMD_OPTS="-Xmx280M"
 
-sub usage {
-	print <<EoF;
+JAVA_OPTS="${JAVA_OXCMD_OPTS} \
+-Djava.awt.headless=true \
+-Dopenexchange.propdir=$PROPERTIESDIR"
 
-This program stores the username and password of the superadmin to the mpasswd file.
+CLASSPATH="-classpath @classpath@"
 
-Usage: $0
- -h,--help       Prints this help text
- -A,--adminuser <adminuser>\t\tAccount name of superadmin (Default: $OXMASTER)
- -P,--adminpass <adminpass>\t\t* Password of superadmin
- -f,--mpasswdfile <mpasswdfile>\t\tpath to mpasswd
-					(Default: $OXMPWFILE)
+umask 066
+exec $JAVA_BIN $JAVA_OPTS $CLASSPATH com.openexchange.admin.console.user.GenerateMasterPasswordCLT $@
 
-Entries marked with an asterisk (*) are mandatory.
-
-EoF
-	exit 0;
-}
-
-sub promptPassword {
-    system("stty -echo");
-    print "Enter password for user $OXMASTER: ";
-    while( <STDIN> ) {
-        chomp;
-        last if $_ ne "";
-    }
-    print "\n";
-    my $PW = $_;
-    system("stty echo");
-	return $PW;
-}
-
-sub encryptPassword {
-	my $pw = shift;
-	return crypt($pw, pack("C2",(int(rand 26)+65),(int(rand 26)+65)));
-}
