- fixed indentation - bugfix id#24541 - Oxinstaller + docs has to be adapted to new configuration layout - removed unused sessioncache.ccf configuration

diff --git a/com.openexchange.admin.console/sbin/oxinstaller.in b/com.openexchange.admin.console/sbin/oxinstaller.in
--- a/com.openexchange.admin.console/sbin/oxinstaller.in
+++ b/com.openexchange.admin.console/sbin/oxinstaller.in
@@ -29,7 +29,7 @@
 #   http://www.open-xchange.com/EN/developer/. The contributing author shall be
 #   given Attribution for the derivative code and a license granting use.
 #
-#    Copyright (C) 2004-2012 Open-Xchange, Inc.
+#    Copyright (C) 2004-2013 Open-Xchange, Inc.
 #    Mail: info@open-xchange.com
 #
 #
@@ -52,22 +52,22 @@ OXFUNCTIONS=@oxfunctions@
 CONFDIR=@confDir@
 
 test -f $OXFUNCTIONS || {
-        echo "missing common shell functions file"
-        exit 1
+    echo "missing common shell functions file"
+    exit 1
 }
 
 . $OXFUNCTIONS
 
 noLongerInUse() {
-        echo option $1 is deprected and not longer in use
+    echo option $1 is deprected and not longer in use
 }
 
 handleIPv6() {
-        if [[ "$1" =~ .*:.* ]]; then
-                echo "[$1]"
-        else
-                echo $1
-        fi
+    if [[ "$1" =~ .*:.* ]]; then
+	echo "[$1]"
+    else
+	echo $1
+    fi
 }
 
 OXHOST=$(hostname -f)
@@ -112,20 +112,15 @@ TMPDIR_PATH=/var/spool/open-xchange/uploads
 TMPDIR_PATH_LONG=tmpdir-path
 AJP_JVM_ROUTE=APP1
 AJP_JVM_ROUTE_LONG=jkroute
-AJP_BIND_ADDR="*"
 AJP_BIND_ADDR_LONG=ajp-bind-port
 UDPDISCOVERYADDR=224.0.0.1
 UDPDISCOVERYADDR_LONG=cache-udp-disc-addr
 UDPDISCOVERYPORT=6780
 UDPDISCOVERYPORT_LONG=cache-udp-disc-port
-UDP_SESS_DISC_PORT=6781
-UDP_SESS_DISC_PORT_LONG=scache-udp-disc-port
 AMCACHEPORT=57461
 AMCACHEPORT_LONG=groupware-cache-port
 GWCACHEPORT=57462
 GWCACHEPORT_LONG=admin-cache-port
-GWSCACHEPORT=58849
-GWSCACHEPORT_LONG=gwsession-cache-port
 SESSIONCONTAINERTIMEOUT="Deprecated"
 SESSIONCONTAINERTIMEOUT_LONG=SesssionContTimeout
 NUMBEROFSESSIONCONTAINERS="Deprecated"
@@ -174,28 +169,30 @@ OLPORT=44335
 OLPORT_LONG=push-outlook-port
 OXCLUSTERNAME="$OXHOST"
 OXCLUSTERNAME_LONG=name-of-oxcluster
+NETWORK_LISTENER_HOST=localhost
+NETWORK_LISTENER_HOST_LONG=network-listener-host
 
 MUSTOPTS="SERVER_NAME CONFIGDB_PASS OXOBJECT_LINK_HOSTNAME SERVER_MEMORY OXCLUSTERNAME"
-LONGOPTS='$SERVER_NAME_LONG:,$IMAP_SERVER_LONG:,$SMTP_SERVER_LONG:,$LOGIN_SOURCE_LONG:,$MAIL_SERVER_SOURCE_LONG:,$TRANSPORT_SERVER_SOURCE_LONG:,$CONFIGDB_USER_LONG:,$CONFIGDB_PASS_LONG:,$CONFIGDB_READ_LONG:,$CONFIGDB_WRITE_LONG:,$CONFIGDB_DBNAME_LONG:,$SERVER_MEMORY_LONG:,$CLT_MEMORY_LONG:,$CONFIGDB_READ_PORT_LONG:,$CONFIGDB_WRITE_PORT_LONG:,$TMPDIR_PATH_LONG:,$MASTER_PASS_LONG:,$MASTER_USER_LONG:,$AJP_JVM_ROUTE_LONG:,$AJP_BIND_ADDR_LONG:,$OXOBJECT_LINK_HOSTNAME_LONG:,$URL_LONG:,$UDPDISCOVERYADDR_LONG:,$UDPDISCOVERYPORT_LONG:,$AMCACHEPORT_LONG:,$GWCACHEPORT_LONG:,$GWSCACHEPORT_LONG:,$OXCLUSTERIP_LONG:,$PUSHMCPORT_LONG:,$OLPORT_LONG:,$SESSIONCONTAINERTIMEOUT_LONG:,$NUMBEROFSESSIONCONTAINERS_LONG:,$MAXSESSION_LONG:,$ISDOUBLELOGINPERMITTED_LONG:,$SESSIONDEFAULTLIFETIME_LONG:,$DISABLE_RMI_AUTH_LONG,$UDP_SESS_DISC_PORT_LONG:,$NO_LICENSE_LONG,$ADD_LICENSE_LONG:,$OXCLUSTERNAME_LONG:'
+LONGOPTS='$SERVER_NAME_LONG:,$IMAP_SERVER_LONG:,$SMTP_SERVER_LONG:,$LOGIN_SOURCE_LONG:,$MAIL_SERVER_SOURCE_LONG:,$TRANSPORT_SERVER_SOURCE_LONG:,$CONFIGDB_USER_LONG:,$CONFIGDB_PASS_LONG:,$CONFIGDB_READ_LONG:,$CONFIGDB_WRITE_LONG:,$CONFIGDB_DBNAME_LONG:,$SERVER_MEMORY_LONG:,$CLT_MEMORY_LONG:,$CONFIGDB_READ_PORT_LONG:,$CONFIGDB_WRITE_PORT_LONG:,$TMPDIR_PATH_LONG:,$MASTER_PASS_LONG:,$MASTER_USER_LONG:,$AJP_JVM_ROUTE_LONG:,$OXOBJECT_LINK_HOSTNAME_LONG:,$URL_LONG:,$UDPDISCOVERYADDR_LONG:,$UDPDISCOVERYPORT_LONG:,$AMCACHEPORT_LONG:,$GWCACHEPORT_LONG:,$OXCLUSTERIP_LONG:,$PUSHMCPORT_LONG:,$OLPORT_LONG:,$SESSIONCONTAINERTIMEOUT_LONG:,$NUMBEROFSESSIONCONTAINERS_LONG:,$MAXSESSION_LONG:,$ISDOUBLELOGINPERMITTED_LONG:,$SESSIONDEFAULTLIFETIME_LONG:,$DISABLE_RMI_AUTH_LONG,$NO_LICENSE_LONG,$ADD_LICENSE_LONG:,$OXCLUSTERNAME_LONG:,$NETWORK_LISTENER_HOST_LONG:,$AJP_BIND_ADDR_LONG:'
 
 usage() {
     echo
     echo "$0 currently knows the following parameters:"
     echo
     local lopts=$(echo $LONGOPTS | sed -e 's/[:,]/ /g')
-    printf '%-22s | %-45s | %-s\n' "Parameter" "Default value" "Possible values"
+    printf '%-23s | %-45s | %-s\n' "Parameter" "Default value" "Possible values"
     echo "--------------------------------------------------------------------------------------------"
     for opt in $lopts; do
-    local rvar=${opt%_LONG}
-    GLOBIGNORE='*'
-    local default="$(eval echo "$rvar")"
-    local possible=$(eval echo ${opt%_LONG}_VALUES)
-    local lopt=$(eval echo $opt)
+	local rvar=${opt%_LONG}
+	GLOBIGNORE='*'
+	local default="$(eval echo "$rvar")"
+	local possible=$(eval echo ${opt%_LONG}_VALUES)
+	local lopt=$(eval echo $opt)
         # echo $opt $rvar $default $lopt
-    printf '%-22s | %-45s | %-s\n' "--$lopt" $default "$possible"
-    GLOBIGNORE=
+	printf '%-23s | %-45s | %-s\n' "--$lopt" $default "$possible"
+	GLOBIGNORE=
     done
-cat<<EOF
+    cat<<EOF
 
 Example:
 
@@ -205,7 +202,6 @@ use -D for Debug mode
 
 EOF
     echo
-#    exit 1
 }
 
 v_setprop() {
@@ -213,11 +209,11 @@ v_setprop() {
     local val="$2"
     local propfile="$3"
     if [ -f $3 ]; then 
-    # echo setting $prop in $propfile
+        # echo setting $prop in $propfile
         echo -n .
         ox_set_property "$prop" "$val" "$propfile"
     else
-    echo
+	echo
         echo skipping configuration of $1 in $3
     fi
 }
@@ -227,12 +223,12 @@ v_comment() {
     local action="$2"
     local propfile="$3"
     if [ -f $3 ]; then
-    # echo $action hash for $prop in $propfile
-    echo -n .
-    ox_comment "$prop" "$action" "$propfile"
+        # echo $action hash for $prop in $propfile
+	echo -n .
+	ox_comment "$prop" "$action" "$propfile"
     else
-    echo
-    echo skipping configuration of $i in $3
+	echo
+	echo skipping configuration of $i in $3
     fi
 }
 
@@ -258,183 +254,179 @@ eval set -- "$TEMP"
 
 while true; do
     case "$1" in
-    -s|--$SERVER_NAME_LONG)
-        SERVER_NAME=$2
-        shift 2
-        ;;
-    -i|--$IMAP_SERVER_LONG)
-        IMAP_SERVER=$2
-        shift 2
-        ;;
-    --$SMTP_SERVER_LONG)
-        SMTP_SERVER=$2
-        shift 2
-        ;;
-    --$LOGIN_SOURCE_LONG)
-        LOGIN_SOURCE=$2
-        shift 2
-        ;;
-    --$MAIL_SERVER_SOURCE_LONG)
-        MAIL_SERVER_SOURCE=$2
-        shift 2
-        ;;
-    --$TRANSPORT_SERVER_SOURCE_LONG)
-        TRANSPORT_SERVER_SOURCE=$2
-        shift 2
-        ;;
-    --$CONFIGDB_USER_LONG)
-        CONFIGDB_USER=$2
-        shift 2
-        ;;
-    --$CONFIGDB_PASS_LONG)
-        CONFIGDB_PASS=$2
-        shift 2
-        ;;
-    --$CONFIGDB_READ_LONG)
-        CONFIGDB_READ=$2
-        shift 2
-        ;;
-    --$CONFIGDB_WRITE_LONG)
-        CONFIGDB_WRITE=$2
-        shift 2
-        ;;
-    --$CONFIGDB_READ_PORT_LONG)
-        CONFIGDB_READ_PORT=$2
-        shift 2
-        ;;
-    --$CONFIGDB_WRITE_PORT_LONG)
-        CONFIGDB_WRITE_PORT=$2
-        shift 2
-        ;;
-    --$CONFIGDB_DBNAME_LONG)
-        CONFIGDB_DBNAME=$2
-        shift 2
-        ;;
-    --$SERVER_MEMORY_LONG)
-        SERVER_MEMORY=$2
-        shift 2
-        ;;
-    --$CLT_MEMORY_LONG)
-        CLT_MEMORY=$2
-        shift 2
-        ;;
-    --$TMPDIR_PATH_LONG)
-        TMPDIR_PATH=$2
-        shift 2
-        ;;
-    --$MASTER_PASS_LONG)
-        MASTER_PASS=$2
-        shift 2
-        ;;
-    --$MASTER_USER_LONG)
-        MASTER_USER=$2
-        shift 2
-        ;;
-    --$DISABLE_RMI_AUTH_LONG)
-        DISABLE_RMI_AUTH=true
-        shift
-        ;;
-    --$AJP_JVM_ROUTE_LONG)
-        AJP_JVM_ROUTE=$2
-        shift 2
-        ;;
-    --$AJP_BIND_ADDR_LONG)
-        AJP_BIND_ADDR=$2
-        shift 2
-        ;;
-    --$OXOBJECT_LINK_HOSTNAME_LONG)
-        OXOBJECT_LINK_HOSTNAME=$2
-        shift 2
-        ;;
-    --$URL_LONG)
-        URL=$2
-        shift 2
-        ;;
-    --$UDPDISCOVERYADDR_LONG)
-        UDPDISCOVERYADDR=$2
-        shift 2
-        ;;
-    --$UDPDISCOVERYPORT_LONG)
-        UDPDISCOVERYPORT=$2
-        shift 2
-        ;;
-    --$UDP_SESS_DISC_PORT_LONG)
-        UDP_SESS_DISC_PORT=$2
-        shift 2
-        ;;
-    --$AMCACHEPORT_LONG)
-        AMCACHEPORT=$2
-        shift 2
-        ;;
-    --$GWCACHEPORT_LONG)
-        GWCACHEPORT=$2
-        shift 2
-        ;;
-    --$GWSCACHEPORT_LONG)
-        GWSCACHEPORT=$2
-        shift 2
-        ;;
-    --$OXCLUSTERIP_LONG)
-        OXCLUSTERIP=$2
-        shift 2
-        ;;
-    --$PUSHMCPORT_LONG)
-        PUSHMCPORT=$2
-        shift 2
-        ;;
-    --$SESSIONCONTAINERTIMEOUT_LONG)
-        noLongerInUse $SESSIONCONTAINERTIMEOUT_LONG
-        shift 2
-        ;;
-    --$NUMBEROFSESSIONCONTAINERS_LONG)
-        noLongerInUse $NUMBEROFSESSIONCONTAINERS_LONG
-        shift 2
-        ;;
-    --$MAXSESSION_LONG)
-        MAXSESSION=$2
-        shift 2
-        ;;
-    --$ISDOUBLELOGINPERMITTED_LONG)
-        noLongerInUse $ISDOUBLELOGINPERMITTED_LONG
-        shift 2
-        ;;
-    --$SESSIONDEFAULTLIFETIME_LONG)
-        SESSIONDEFAULTLIFETIME=$2
-        shift 2
-        ;;
-    --$OLPORT_LONG)
-        OLPORT=$2
-        shift 2
-        ;;
-    --$ADD_LICENSE_LONG)
-        ADD_LICENSE=$2
-        shift 2
-        ;;
-    --$NO_LICENSE_LONG)
-        NO_LICENSE=true
-        shift
-        ;;
-    --$OXCLUSTERNAME_LONG)
-        OXCLUSTERNAME=$2
-        shift 2
-        ;;
-    -h|--help)
-        usage
-        exit
-        shift
-        ;;
-    -D)
-        set -x
-        shift
-        ;;
-    --)
-        shift
-        break
-        ;;
-    *)
-        die "Internal error!"
-        exit 1
-        ;;
+	-s|--$SERVER_NAME_LONG)
+          SERVER_NAME=$2
+          shift 2
+          ;;
+	-i|--$IMAP_SERVER_LONG)
+          IMAP_SERVER=$2
+          shift 2
+          ;;
+	--$SMTP_SERVER_LONG)
+          SMTP_SERVER=$2
+          shift 2
+          ;;
+	--$LOGIN_SOURCE_LONG)
+          LOGIN_SOURCE=$2
+          shift 2
+          ;;
+	--$MAIL_SERVER_SOURCE_LONG)
+          MAIL_SERVER_SOURCE=$2
+          shift 2
+          ;;
+	--$TRANSPORT_SERVER_SOURCE_LONG)
+          TRANSPORT_SERVER_SOURCE=$2
+          shift 2
+          ;;
+	--$CONFIGDB_USER_LONG)
+          CONFIGDB_USER=$2
+          shift 2
+          ;;
+	--$CONFIGDB_PASS_LONG)
+          CONFIGDB_PASS=$2
+          shift 2
+          ;;
+	--$CONFIGDB_READ_LONG)
+          CONFIGDB_READ=$2
+          shift 2
+          ;;
+	--$CONFIGDB_WRITE_LONG)
+          CONFIGDB_WRITE=$2
+          shift 2
+          ;;
+	--$CONFIGDB_READ_PORT_LONG)
+          CONFIGDB_READ_PORT=$2
+          shift 2
+          ;;
+	--$CONFIGDB_WRITE_PORT_LONG)
+          CONFIGDB_WRITE_PORT=$2
+          shift 2
+          ;;
+	--$CONFIGDB_DBNAME_LONG)
+          CONFIGDB_DBNAME=$2
+          shift 2
+          ;;
+	--$SERVER_MEMORY_LONG)
+          SERVER_MEMORY=$2
+          shift 2
+          ;;
+	--$CLT_MEMORY_LONG)
+          CLT_MEMORY=$2
+          shift 2
+          ;;
+	--$TMPDIR_PATH_LONG)
+          TMPDIR_PATH=$2
+          shift 2
+          ;;
+	--$MASTER_PASS_LONG)
+          MASTER_PASS=$2
+          shift 2
+          ;;
+	--$MASTER_USER_LONG)
+          MASTER_USER=$2
+          shift 2
+          ;;
+	--$DISABLE_RMI_AUTH_LONG)
+          DISABLE_RMI_AUTH=true
+          shift
+          ;;
+	--$AJP_JVM_ROUTE_LONG)
+          AJP_JVM_ROUTE=$2
+          shift 2
+          ;;
+	--$AJP_BIND_ADDR_LONG)
+          NETWORK_LISTENER_HOST=$2
+          shift 2
+          ;;
+	--$NETWORK_LISTENER_HOST_LONG)
+          NETWORK_LISTENER_HOST=$2
+          shift 2
+          ;;
+	--$OXOBJECT_LINK_HOSTNAME_LONG)
+          OXOBJECT_LINK_HOSTNAME=$2
+          shift 2
+          ;;
+	--$URL_LONG)
+          URL=$2
+          shift 2
+          ;;
+	--$UDPDISCOVERYADDR_LONG)
+          UDPDISCOVERYADDR=$2
+          shift 2
+          ;;
+	--$UDPDISCOVERYPORT_LONG)
+          UDPDISCOVERYPORT=$2
+          shift 2
+          ;;
+	--$AMCACHEPORT_LONG)
+          AMCACHEPORT=$2
+          shift 2
+          ;;
+	--$GWCACHEPORT_LONG)
+          GWCACHEPORT=$2
+          shift 2
+          ;;
+	--$OXCLUSTERIP_LONG)
+          OXCLUSTERIP=$2
+          shift 2
+          ;;
+	--$PUSHMCPORT_LONG)
+          PUSHMCPORT=$2
+          shift 2
+          ;;
+	--$SESSIONCONTAINERTIMEOUT_LONG)
+          noLongerInUse $SESSIONCONTAINERTIMEOUT_LONG
+          shift 2
+          ;;
+	--$NUMBEROFSESSIONCONTAINERS_LONG)
+          noLongerInUse $NUMBEROFSESSIONCONTAINERS_LONG
+          shift 2
+          ;;
+	--$MAXSESSION_LONG)
+          MAXSESSION=$2
+          shift 2
+          ;;
+	--$ISDOUBLELOGINPERMITTED_LONG)
+          noLongerInUse $ISDOUBLELOGINPERMITTED_LONG
+          shift 2
+          ;;
+	--$SESSIONDEFAULTLIFETIME_LONG)
+          SESSIONDEFAULTLIFETIME=$2
+          shift 2
+          ;;
+	--$OLPORT_LONG)
+          OLPORT=$2
+          shift 2
+          ;;
+	--$ADD_LICENSE_LONG)
+          ADD_LICENSE=$2
+          shift 2
+          ;;
+	--$NO_LICENSE_LONG)
+          NO_LICENSE=true
+          shift
+          ;;
+	--$OXCLUSTERNAME_LONG)
+          OXCLUSTERNAME=$2
+          shift 2
+          ;;
+	-h|--help)
+          usage
+          exit
+          shift
+          ;;
+	-D)
+          set -x
+          shift
+          ;;
+	--)
+          shift
+          break
+          ;;
+	*)
+          die "Internal error!"
+          exit 1
+          ;;
     esac
 done
 
@@ -452,7 +444,7 @@ for opt in $MUSTOPTS; do
     opt_var_long=$(eval echo \$${opt}_LONG)
     if [ -z "$opt_var" ]; then
         usage;
-    die "missing required option --$opt_var_long"
+	die "missing required option --$opt_var_long"
     fi
 done
 
@@ -463,15 +455,15 @@ for opt in $ALLOPTS; do
     opt_var_long=$(eval echo \$${opt}_LONG)
     opt_var_values=$(eval echo \$${opt}_VALUES)
     if [ -n "$opt_var_values" ]; then
-    found=
-    for val in $opt_var_values; do
-        if [ "$val" == "$opt_var" ]; then
-        found=$val
-        fi
-    done
-    if [ -z "$found" ]; then
-        die "\"$opt_var\" is not a valid option to --$opt_var_long"
-    fi
+	found=
+	for val in $opt_var_values; do
+	    if [ "$val" == "$opt_var" ]; then
+		found=$val
+	    fi
+	done
+	if [ -z "$found" ]; then
+	    die "\"$opt_var\" is not a valid option to --$opt_var_long"
+	fi
     fi
 done
 
@@ -504,7 +496,7 @@ setup()
 
     GLOBIGNORE='*'
     v_setprop com.openexchange.server.backendRoute "$AJP_JVM_ROUTE" ${CONFDIR}/server.properties
-    v_setprop com.openexchange.connector.networkListenerHost "$AJP_BIND_ADDR" ${CONFDIR}/server.properties
+    v_setprop com.openexchange.connector.networkListenerHost "$NETWORK_LISTENER_HOST" ${CONFDIR}/server.properties
     GLOBIGNORE=
 
     v_setprop object_link "http://$OXOBJECT_LINK_HOSTNAME/#m=[module]&i=[object]&f=[folder]" ${CONFDIR}/notification.properties
@@ -524,7 +516,7 @@ setup()
     v_setprop writeUrl $EVAL_SQL_URL ${CONFDIR}/configdb.properties
 
     if [ "$CONFIGDB_READ" != "$CONFIGDB_WRITE" ]; then
-    v_setprop useSeparateWrite "true" ${CONFDIR}/configdb.properties
+	v_setprop useSeparateWrite "true" ${CONFDIR}/configdb.properties
     fi
 
     v_setprop readProperty.1 "user=$CONFIGDB_USER" ${CONFDIR}/configdb.properties
@@ -549,9 +541,6 @@ setup()
 
     v_cache_hosting ${CONFDIR}/cache.ccf LTCP $UDPDISCOVERYPORT
     v_setprop jcs.auxiliary.LTCP.attributes.TcpListenerPort $GWCACHEPORT ${CONFDIR}/cache.ccf
-
-    v_cache_hosting ${CONFDIR}/sessioncache.ccf SessionLTCP $UDP_SESS_DISC_PORT
-    v_setprop jcs.auxiliary.SessionLTCP.attributes.TcpListenerPort $GWSCACHEPORT ${CONFDIR}/sessioncache.ccf
 
     v_setprop com.openexchange.push.udp.senderAddress "$OXCLUSTERIP" ${CONFDIR}/push-udp.properties
     v_setprop com.openexchange.push.udp.multicastAddress "$UDPDISCOVERYADDR" ${CONFDIR}/push-udp.properties
@@ -584,7 +573,7 @@ setup()
         else
             echo "using $MASTER_USER as master account"
             /opt/open-xchange/sbin/generatempasswd -A $MASTER_USER \
-            -f /opt/open-xchange/etc/mpasswd -P "$MASTER_PASS" >/dev/null
+		-f /opt/open-xchange/etc/mpasswd -P "$MASTER_PASS" >/dev/null
         fi
     else
         v_setprop MASTER_AUTHENTICATION_DISABLED true ${CONFDIR}/AdminDaemon.properties
@@ -604,21 +593,21 @@ addLicense() {
 # license file ops
 if [ -n "$ADD_LICENSE" ]; then
     if [ ! -e $LICENSEFILE ]; then
-    addLicense "$ADD_LICENSE" 1
+	addLicense "$ADD_LICENSE" 1
     else
-    if ! grep "$ADD_LICENSE" $LICENSEFILE >/dev/null; then
-        cnt=1
-        while [ true ]; do
-        lstr="com.openexchange.licensekey.${cnt}"
-        if ! grep -E "^$lstr" $LICENSEFILE > /dev/null; then
-            addLicense "$ADD_LICENSE" $cnt
-            break
-        fi
-        cnt=$(( $cnt + 1 ))
-        done
-    else
-        echo "skipping license $ADD_LICENSE, it's already in $LICENSEFILE"
-    fi
+	if ! grep "$ADD_LICENSE" $LICENSEFILE >/dev/null; then
+	    cnt=1
+	    while [ true ]; do
+		lstr="com.openexchange.licensekey.${cnt}"
+		if ! grep -E "^$lstr" $LICENSEFILE > /dev/null; then
+		    addLicense "$ADD_LICENSE" $cnt
+		    break
+		fi
+		cnt=$(( $cnt + 1 ))
+	    done
+	else
+	    echo "skipping license $ADD_LICENSE, it's already in $LICENSEFILE"
+	fi
     fi
 fi
 
