Fix for bug 24581: Using only special Java options for CLTs in all scripts starting some CLT

diff --git a/com.openexchange.admin.reseller.console/sbin/createadmin.in b/com.openexchange.admin.reseller.console/sbin/createadmin.in
--- a/com.openexchange.admin.reseller.console/sbin/createadmin.in
+++ b/com.openexchange.admin.reseller.console/sbin/createadmin.in
@@ -53,8 +53,8 @@ OXFUNCTIONS=@oxfunctions@
 OXCONFIG=@oxscriptconf@
 
 test -f $OXFUNCTIONS || {
-	echo "missing common shell functions file"
-	exit 1
+    echo "missing common shell functions file"
+    exit 1
 }
 
 . $OXFUNCTIONS
@@ -99,7 +99,9 @@ case "$BNAME" in
 esac
 
 JAVAMAIN="com.openexchange.admin.reseller.console.${ACTION}"
+
 ADMINCP=$(for jar in $LIBPATH/*.jar; do
     echo -n "${jar}:"
     done)
-$JAVA_BIN $JAVA_OXCMD_OPTS $JAVA_XTRAOPTS -classpath ${ADMINCP} $JAVAMAIN "$@"
+
+$JAVA_BIN $JAVA_OXCMD_OPTS -classpath ${ADMINCP} $JAVAMAIN "$@"
diff --git a/com.openexchange.admin.user.copy.console/sbin/usercopy.in b/com.openexchange.admin.user.copy.console/sbin/usercopy.in
--- a/com.openexchange.admin.user.copy.console/sbin/usercopy.in
+++ b/com.openexchange.admin.user.copy.console/sbin/usercopy.in
@@ -53,8 +53,8 @@ OXFUNCTIONS=@oxfunctions@
 OXCONFIG=@oxscriptconf@
 
 test -f $OXFUNCTIONS || {
-	echo "missing common shell functions file"
-	exit 1
+    echo "missing common shell functions file"
+    exit 1
 }
 
 . $OXFUNCTIONS
@@ -63,11 +63,12 @@ test -f $OXCONFIG && . $OXCONFIG
 
 ox_set_JAVA_BIN
 
-
 test -z "$LIBPATH"          && LIBPATH=${PREFIX}jar
 
 JAVAMAIN="com.openexchange.admin.user.copy.console.UserCopy"
+
 ADMINCP=$(for jar in $LIBPATH/*.jar; do
     echo -n "${jar}:"
     done)
-$JAVA_BIN $JAVA_OXCMD_OPTS $JAVA_XTRAOPTS -classpath ${ADMINCP} $JAVAMAIN "$@"
+
+$JAVA_BIN $JAVA_OXCMD_OPTS -classpath ${ADMINCP} $JAVAMAIN "$@"
