Bug #51074: Improved charmap detection
- all of en_US.UTF-8, .utf8, .utf-8, .UTF_8 will result in a valid UTF-8
  charmap
- simply query via locale charmap

diff --git a/oxscripts/sbin/open-xchange.in b/oxscripts/sbin/open-xchange.in
--- a/oxscripts/sbin/open-xchange.in
+++ b/oxscripts/sbin/open-xchange.in
@@ -116,11 +116,11 @@ then
 fi
 
 # Bug 51074: wrong locale will break encoding of started processes
-LC_CTYPE=$(locale | sed -ne 's/^LC_CTYPE="\?\([^"]*\)"\?$/\1/p')
-if ! [[ "${LC_CTYPE}" =~ .*UTF-8 ]]
+charmap=$(locale charmap)
+if ! [[ "${charmap}" == "UTF-8" ]]
 then
-  echo "WARNING: Couldn't detect proper unicode locale for category LC_CTYPE!" >> ${CONSOLELOG}
-  echo "WARNING: Current LC_CTYPE: ${LC_CTYPE} will cause encoding problems!"  >> ${CONSOLELOG}
+  echo "WARNING: Couldn't detect proper unicode charmap in locale category LC_CTYPE." >> ${CONSOLELOG}
+  echo "WARNING: Current charmap: \"${charmap}\" might cause encoding problems."  >> ${CONSOLELOG}
 fi
 
 exec $JAVA_BIN $JAVA_OPTS $CLASSPATH -jar /opt/open-xchange/bundles/org.eclipse.osgi_3.11.0.v20160603-1336.jar -configuration file:$OSGIPATH >> $CONSOLELOG 2>&1
